services:
  postgres:
    image: postgres:16
    container_name: nutri-postgres
    environment:
      POSTGRES_DB: nutridb
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: