spring.application.name=nutri-api

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/nutridb
spring.datasource.username=nutri
spring.datasource.password=nutri123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=3f8a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1
jwt.expiration=86400000